/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.7.0.0 (NJsonSchema v10.1.24.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export interface LoginUserQuery {
    email: string | null;
    password: string | null;
}

export interface LoggedUserDto {
    id: string | null;
    userName: string | null;
    learningPath: string | null;
}

export interface LoggedUserViewModel {
    loggedUser: LoggedUserDto;
    token: string | null;
    refreshToken: string | null;
}

export interface ForgotPasswordCommand {
    email: string | null;
}

export interface ResetPasswordCommand {
    passwordToken: string | null;
    newPassword: string | null;
    confirmNewPassword: string | null;
}

export interface CheckPasswordTokenQuery {
    passwordToken: string | null;
}

export interface CoursesListItemDto {
    id: string | null;
    title: string | null;
    subtitle: string | null;
    creator: string | null;
    creationDate: Date;
    status: string | null;
    duration: number;
    lectureCount: number;
}

export interface CoursesListResult {
    readonly totalItems: number;
    readonly items: CoursesListItemDto[] | null;
}

export interface CoursesListViewModel {
    queryResult: CoursesListResult;
}

export interface CreateCourseCommand {
    title: string | null;
}

export interface CommandResponse {
    value: string | null;
}

export interface UpdateCourseCommand {
    courseId: string | null;
    title: string | null;
    subtitle: string | null;
    description: string | null;
    courseLearnedSkills: string[] | null;
}

export interface CourseLearnedSkillDto {
    readonly id: number;
    readonly name: string | null;
}

export interface CourseDto {
    id: string | null;
    title: string | null;
    subtitle: string | null;
    creator: string | null;
    description: string | null;
    creationDate: Date;
    status: string | null;
    duration: number;
    lectureCount: number;
    courseLearnedSkills: CourseLearnedSkillDto[] | null;
    isEditable: boolean;
    readonly isPublished: boolean;
}

export interface CourseErrorDto {
    moduleId: string | null;
    lectureId: string | null;
    error: string | null;
}

export interface CourseViewModel {
    course: CourseDto;
    courseErrors: CourseErrorDto[] | null;
}

export interface ModuleDto {
    id: string | null;
    name: string | null;
    order: number;
    duration: number;
}

export interface LectureDto {
    id: string | null;
    title: string | null;
    order: number;
    duration: number;
    lectureType: string | null;
    moduleId: string | null;
    content: string | null;
    videoUrl: string | null;
}

export interface ModuleDetailDto {
    moduleInfo: ModuleDto;
    lectures: LectureDto[] | null;
}

export interface CourseContentDto {
    courseId: string | null;
    modules: ModuleDetailDto[] | null;
}

export interface CourseContentViewModel {
    courseContent: CourseContentDto;
}

export interface CoursesManagementOrderByDto {
    readonly id: number;
    readonly name: string | null;
}

export interface CoursesManagementAuthorFilterDto {
    readonly id: string | null;
    readonly name: string | null;
}

export interface LearningPathFilterDto {
    readonly id: string | null;
    readonly name: string | null;
}

export interface StatusFilterDto {
    readonly id: number;
    readonly name: string | null;
}

export interface CoursesFiltersViewModel {
    orderByFiltersList: CoursesManagementOrderByDto[] | null;
    orderByDefaultValue: number;
    authorsFiltersList: CoursesManagementAuthorFilterDto[] | null;
    learningPathsFiltersList: LearningPathFilterDto[] | null;
    statusFiltersList: StatusFilterDto[] | null;
}

export interface ModuleOrderDto {
    moduleId: string | null;
    order: number;
}

export interface UpdateModulesOrdersCommand {
    courseId: string | null;
    modulesOrders: ModuleOrderDto[] | null;
}

export interface PublishCourseCommand {
    courseId: string | null;
}

export interface UnpublishCourseCommand {
    courseId: string | null;
}

export interface DraftCourseCommand {
    courseId: string | null;
}

export interface LastCreatedCourseDto {
    courseId: string | null;
    courseTitle: string | null;
    courseCreator: string | null;
    creationDate: Date;
}

export interface LastPublishedCourseDto {
    courseId: string | null;
    courseTitle: string | null;
    coursePublisher: string | null;
    publicationDate: Date | null;
}

export interface CoursesInfoViewModel {
    lastCreatedCourse: LastCreatedCourseDto;
    lastPublishedCourse: LastPublishedCourseDto;
    courseCount: number;
}

export interface LearnerLastCourseProgressDto {
    courseId: string | null;
    courseTitle: string | null;
    totalDuration: number;
    completedDuration: number;
}

export interface LearnerInfoViewModel {
    lastCourseProgress: LearnerLastCourseProgressDto;
}

export interface LearnerCourseDto {
    id: string | null;
    title: string | null;
    subtitle: string | null;
    description: string | null;
    creator: string | null;
    creationDate: Date;
    duration: number;
    lectureCount: number;
}

export interface LearnerCourseProgressDto {
    readonly courseId: string | null;
    readonly duration: number;
}

export interface LearnerCoursesListResult {
    readonly totalItems: number;
    readonly items: LearnerCourseDto[] | null;
    readonly progress: LearnerCourseProgressDto[] | null;
}

export interface LearnerCoursesListViewModel {
    queryResult: LearnerCoursesListResult;
}

export interface LearnerLectureDto {
    id: string | null;
    title: string | null;
    order: number;
    duration: number;
    lectureType: string | null;
    moduleId: string | null;
    content: string | null;
    videoUrl: string | null;
}

export interface LearnerModuleDto {
    id: string | null;
    name: string | null;
    order: number;
    duration: number;
    lectures: LearnerLectureDto[] | null;
}

export interface LearnerCourseContentDto {
    courseId: string | null;
    title: string | null;
    duration: number;
    modules: LearnerModuleDto[] | null;
}

export interface LearnerCourseContentViewModel {
    courseContent: LearnerCourseContentDto;
    lastLectureId: string | null;
}

export interface LearnerCourseLearnedSkillDto {
    id: number;
    name: string | null;
}

export interface LearnerLectureOverviewDto {
    id: string | null;
    title: string | null;
    order: number;
    duration: number;
    lectureType: string | null;
}

export interface LearnerModuleOverviewDto {
    id: string | null;
    name: string | null;
    order: number;
    duration: number;
    lectures: LearnerLectureOverviewDto[] | null;
}

export interface LearnerCourseOverviewDto {
    id: string | null;
    title: string | null;
    subtitle: string | null;
    description: string | null;
    creator: string | null;
    creationDate: Date;
    duration: number;
    lectureCount: number;
    courseLearnedSkills: LearnerCourseLearnedSkillDto[] | null;
    modules: LearnerModuleOverviewDto[] | null;
}

export interface LearnerCourseOverviewViewModel {
    courseOverview: LearnerCourseOverviewDto;
}

export interface AddLearnerAccessHistoryCommand {
    lectureId: string | null;
}

export interface CompletedLecturesViewModel {
    completedLectures: string[] | null;
}

export interface CompleteLectureCommand {
    lectureId: string | null;
}

export interface LearnerCourseOrderByDto {
    readonly id: number;
    readonly name: string | null;
}

export interface LearnerCourseAuthorFilterDto {
    readonly id: string | null;
    readonly name: string | null;
}

export interface LearnerCoursesFiltersViewModel {
    orderByFiltersList: LearnerCourseOrderByDto[] | null;
    orderByDefaultValue: number;
    authorsFiltersList: LearnerCourseAuthorFilterDto[] | null;
}

export interface CourseLearningPathDto {
    readonly id: string | null;
    readonly name: string | null;
}

export interface GetCourseLearningPathsListVm {
    courseLearningPathsIds: string[] | null;
    learningPaths: CourseLearningPathDto[] | null;
}

export interface UpdateCourseLearningPathsCommand {
    courseId: string | null;
    learningPathsIds: string[] | null;
}

export interface LearningPathDto {
    id: string | null;
    name: string | null;
    description: string | null;
    courseCount: number;
    learnerCount: number;
    isDeletable: boolean;
}

export interface LearningPathsViewModel {
    learningPaths: LearningPathDto[] | null;
}

export interface CreateLearningPathCommand {
    name: string | null;
}

export interface UpdateLearningPathCommand {
    learningPathId: string | null;
    name: string | null;
    description: string | null;
}

export interface LearningPathViewModel {
    learningPath: LearningPathDto;
}

export interface CourseForLearningPathDto {
    id: string | null;
    title: string | null;
    creator: string | null;
    creationDate: Date;
    status: string | null;
    duration: number;
    order: number;
}

export interface LearningPathCoursesViewModel {
    courses: CourseForLearningPathDto[] | null;
}

export interface OtherCoursesToAddViewModel {
    courses: CourseForLearningPathDto[] | null;
}

export interface CourseOrderDto {
    courseId: string | null;
    order: number;
}

export interface UpdateCoursesOrdersCommand {
    learningPathId: string | null;
    coursesOrders: CourseOrderDto[] | null;
}

export interface LearnerForLearningPathDto {
    id: string | null;
    userName: string | null;
    email: string | null;
    status: string | null;
}

export interface LearningPathLearnersViewModel {
    learners: LearnerForLearningPathDto[] | null;
}

export interface LearnerCompletedCoursesDto {
    completedCourses: string[] | null;
    learningPathCourseCount: number;
}

export interface LearnerProgressViewModel {
    learnerCompletedCourses: LearnerCompletedCoursesDto;
}

export interface AddCoursesToLearningPathCommand {
    learningPathId: string | null;
    coursesIds: string[] | null;
}

export interface RemoveCourseFromLearningPathCommand {
    learningPathId: string | null;
    courseId: string | null;
}

export interface LearningPathForDashboardDto {
    name: string | null;
    courseCount: number;
    learnerCount: number;
}

export interface LearningPathsInfoViewModel {
    learningPaths: LearningPathForDashboardDto[] | null;
}

export interface LectureViewModel {
    lecture: LectureDto;
}

export interface CreateLectureCommand {
    title: string | null;
    lectureType: string | null;
    order: number;
    duration: number;
    content: string | null;
    moduleId: string | null;
}

export interface UpdateLectureCommand {
    lectureId: string | null;
    title: string | null;
    duration: number;
    content: string | null;
}

export interface ModuleViewModel {
    module: ModuleDto;
}

export interface CreateModuleCommand {
    name: string | null;
    order: number;
    courseId: string | null;
}

export interface UpdateModuleCommand {
    moduleId: string | null;
    name: string | null;
}

export interface LectureOrderDto {
    lectureId: string | null;
    order: number;
}

export interface UpdateLecturesOrdersCommand {
    moduleId: string | null;
    lecturesOrders: LectureOrderDto[] | null;
}

export interface NotificationDto {
    readonly id: string | null;
    readonly notificationEvent: string | null;
    readonly subject: string | null;
    readonly body: string | null;
    readonly creationDate: Date;
    readonly isRead: boolean;
}

export interface NotificationsListViewModel {
    notifications: NotificationDto[] | null;
}

export interface NotificationTemplateDto {
    id: string | null;
    type: string | null;
    event: string | null;
    isActivated: boolean;
}

export interface NotificationTemplatesViewModel {
    notificationTemplates: NotificationTemplateDto[] | null;
}

export interface ToggleNotificationActivationCommand {
    templateId: string | null;
    isActivated: boolean;
}

export interface NotificationTemplateViewModel {
    notificationTemplate: NotificationTemplateDto;
}

export interface OrganizationInfoViewModel {
    organizationName: string | null;
    subscriptionPlan: string | null;
    maxStorage: number;
    currentStorage: number;
    currentUsersCount: number;
}

export interface UpdateOrganizationInfoCommand {
    organizationName: string | null;
}

export interface InitSigningUpCommand {
    email: string | null;
}

export interface CompleteOrganizationSigningUpCommand {
    signingUpToken: string | null;
    organizationName: string | null;
    userName: string | null;
    password: string | null;
    confirmPassword: string | null;
}

export interface CheckOrganizationSigningUpTokenQuery {
    signingUpToken: string | null;
}

export interface StorageInfoDto {
    maximumStorage: number;
    currentStorage: number;
}

export interface StorageInfoViewModel {
    storageInfo: StorageInfoDto;
}

export interface UserForProfileDto {
    userName: string | null;
    email: string | null;
    learningPath: string | null;
    roles: string | null;
}

export interface UserProfileViewModel {
    currentUser: UserForProfileDto;
}

export interface UpdateCurrentUserInfoCommand {
    userName: string | null;
}

export interface UpdateCurrentUserPasswordCommand {
    newPassword: string | null;
    confirmNewPassword: string | null;
}

export interface CompleteUserSigningUpCommand {
    signingUpToken: string | null;
    userName: string | null;
    password: string | null;
    confirmPassword: string | null;
}

export interface CheckUserSigningUpTokenQuery {
    signingUpToken: string | null;
}

export interface InviteMembersCommand {
    emails: string[] | null;
    learningPathId: string | null;
}

export interface UsersListItemDto {
    id: string | null;
    email: string | null;
    userName: string | null;
    learningPath: string | null;
    roles: string | null;
    status: string | null;
}

export interface UsersListViewModel {
    users: UsersListItemDto[] | null;
}

export interface UpdateUserLearningPathCommand {
    userId: string | null;
    learningPathId: string | null;
}

export interface UserDto {
    id: string | null;
    email: string | null;
    userName: string | null;
    learningPathId: string | null;
    rolesIds: string[] | null;
    status: string | null;
    isBlocked: boolean;
    invitedBy: string | null;
    creationDate: Date;
}

export interface LearningPathForUserDto {
    readonly id: string | null;
    readonly name: string | null;
}

export interface RoleForUserDto {
    readonly id: string | null;
    readonly name: string | null;
    readonly description: string | null;
}

export interface UserViewModel {
    user: UserDto;
    learningPaths: LearningPathForUserDto[] | null;
    roles: RoleForUserDto[] | null;
}

export interface UpdateUserRolesCommand {
    userId: string | null;
    rolesIds: string[] | null;
}

export interface BlockUserCommand {
    userId: string | null;
}

export interface UnblockUserCommand {
    userId: string | null;
}

export interface UserCountInfoDto {
    maximumUsers: number;
    currentUserCount: number;
}

export interface UserCountInfoViewModel {
    userCountInfo: UserCountInfoDto;
}

export interface FileParameter {
    data: any;
    fileName: string;
}